name = "liquid-membrane"
main = "sites/myc.md/worker.ts"
compatibility_date = "2026-05-07"
workers_dev = true

routes = [
  { pattern = "myc.md/*", zone_name = "myc.md" },
  { pattern = "*.myc.md/*", zone_name = "myc.md" }
]

[[kv_namespaces]]
binding = "MYC_PUBLISHED"
id = "cafe147ea7694d1db6e7d86f076ee0ff"
