import { crypto } from "jsr:@std/crypto";
import { encodeHex } from "jsr:@std/encoding/hex";
import { join } from "jsr:@std/path";
import { ensureDir } from "jsr:@std/fs";

const INPUT_PATH = Deno.args[0] || "phi_receipt_fixture.json";
const OUTPUT_DIR = join(Deno.cwd(), "substrates", "liquid", "receipts");

async function sha256(data: string): Promise<string> {
  const encoder = new TextEncoder();
  const hashBuffer = await crypto.subtle.digest(
    "SHA-256",
    encoder.encode(data),
  );
  return encodeHex(hashBuffer);
}

async function importReceipt() {
  const rawReceipt = await Deno.readTextFile(INPUT_PATH);
  const receiptObj = JSON.parse(rawReceipt);

  if (receiptObj.type !== "PHI_RECEIPT") {
    throw new Error("Invalid input: not a PHI_RECEIPT");
  }

  await ensureDir(OUTPUT_DIR);

  // Generate a PN_CAD_DESCRIPTOR style markdown
  const content = `---
chord: ["oct:6.6", "oct:3.3"]
energy: 1.0
tension: "Deterministic Genesis Receipt Integration"
type: "SealedReceiptDescriptor"
intent_hash: "${receiptObj.intent_hash}"
status: "${receiptObj.status}"
derived_phase: ${receiptObj.derived_phase}
signature: "${receiptObj.receipt_signature}"
---

# Genesis Receipt: ${receiptObj.intent_hash.substring(0, 8)}

This receipt was deterministically generated by the Genesis physics kernel in
response to a liquid PHI_INTENT.

- **Status**: ${receiptObj.status}
- **Derived Phase**: ${receiptObj.derived_phase}
- **Timestamp**: ${receiptObj.timestamp}

> [!SUCCESS]
> Phase verified. Signature:
> \`${receiptObj.receipt_signature}\`
`;

  // Use a hash of the content to generate a deterministic file name
  const contentHash = (await sha256(content)).substring(0, 12);
  const fileName = `receipt.${contentHash}.myc.md`;
  const outPath = join(OUTPUT_DIR, fileName);

  await Deno.writeTextFile(outPath, content);
  console.log(`[MYC] Imported PHI_RECEIPT. Wrote descriptor to ${outPath}`);
}

importReceipt().catch(console.error);
